import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default  function Home() {
  const getinfoo = async()=>{
   const res = await fetch('http://localhost:3000/api/getinfo')
   const info = await res.json()
   console.log('====================================');
   console.log("info",info);
   console.log('====================================');
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <div>
           <h1>Hello user pleace Enter url adress</h1>
       <input type={'url'}></input>
       <button  onClick={getinfoo}>Go</button>
        </div>
        </div>
      </main>
    </>
  )
}
